// Package glama wraps the Glama MCP API REST API (https://glama.ai/api/mcp).
//
// Generated by scripts/openapi-to-coily.py from https://glama.ai/api/mcp/openapi.json. Do not edit
// by hand: re-run the generator. The generator emits one cli.Command per
// (path, method) tuple, grouped by OpenAPI tag. Path parameters are
// positional in declaration order; query parameters become --<name>
// string flags; request bodies arrive via --body (literal | @file | -).
// Responses stream to stdout pretty-printed (JSON) or verbatim (other).
//
// Two persistent root flags, --query (JMESPath projection) and --output
// (json|yaml|text), fold coily's REST projection rail (coilyco-bridge/coily#46)
// into every leaf via restfmt. When neither is set the response is emitted
// byte-for-byte as before. An op that already owns an API --query parameter
// exposes the projection as --jq instead, mirroring the gh-rest --jq rail.
//
// Bearer auth from AWS SSM at /glama/api-key, fetched only for endpoints that declare it.
package glama

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"forgejo.coilysiren.me/coilyco-bridge/coily/cmd/coily/restfmt"
	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/audit"
	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/shell"
	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/verb"
	"github.com/urfave/cli/v3"
)

const (
	apiBase     = "https://glama.ai/api/mcp"
	httpTimeout = 60 * time.Second
	ssmAPIKey   = "/glama/api-key" //nolint:gosec // SSM path, not a credential
)

// Command returns the cli.Command tree for `coily pkg glama`.
func Command(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "glama",
		Usage: "Glama MCP API directory + telemetry.",
		Flags: []cli.Flag{
			// urfave/cli v3 flags propagate to every subcommand by default
			// (Local defaults false), so these reach every generated leaf. A
			// leaf that declares a same-named local flag shadows them.
			&cli.StringFlag{Name: "query", Usage: "JMESPath projection applied to the JSON response (coily#46)"},
			&cli.StringFlag{Name: "output", Usage: "output format: json (default), yaml, text (coily#46)"},
		},
		Commands: []*cli.Command{
			groupInstances(r, w),
			groupServers(r, w),
			groupTelemetry(r, w),
		},
	}
}

func groupInstances(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "instances",
		Usage: "Glama MCP API endpoints tagged instances.",
		Commands: []*cli.Command{
			opInstancesGetV1Instances(r, w),
		},
	}
}

func groupServers(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "servers",
		Usage: "Glama MCP API endpoints tagged servers.",
		Commands: []*cli.Command{
			opServersGetV1Servers(r, w),
			opServersGetV1Attributes(r, w),
			opServersGetV1ServersByNamespaceBySlug(r, w),
		},
	}
}

func groupTelemetry(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "telemetry",
		Usage: "Glama MCP API endpoints tagged telemetry.",
		Commands: []*cli.Command{
			opTelemetryPostV1TelemetryUsage(r, w),
		},
	}
}

func opInstancesGetV1Instances(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "get-v1-instances",
		Usage: "Hosted MCP server instances",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.glama.instances.get-v1-instances",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					path := "/v1/instances"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true, c.String("query"), c.String("output"))
				},
			},
			w,
		),
	}
}

func opServersGetV1Servers(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "get-v1-servers",
		Usage: "GET /v1/servers",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "after", Usage: "query: "},
			&cli.StringFlag{Name: "first", Usage: "query: "},
			&cli.StringFlag{Name: "query", Usage: "query: Free text search query"},
			&cli.StringFlag{Name: "jq", Usage: "JMESPath projection applied to the JSON response; --jq here because this op owns an API --query (coily#46)"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.glama.servers.get-v1-servers",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("after") {
						m["--after"] = c.String("after")
					}
					if c.IsSet("first") {
						m["--first"] = c.String("first")
					}
					if c.IsSet("query") {
						m["--query"] = c.String("query")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					path := "/v1/servers"
					q := url.Values{}
					if c.IsSet("after") {
						q.Set("after", c.String("after"))
					}
					if c.IsSet("first") {
						q.Set("first", c.String("first"))
					}
					if c.IsSet("query") {
						q.Set("query", c.String("query"))
					}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, false, c.String("jq"), c.String("output"))
				},
			},
			w,
		),
	}
}

func opServersGetV1Attributes(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "get-v1-attributes",
		Usage: "MCP server attributes",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.glama.servers.get-v1-attributes",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					path := "/v1/attributes"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, false, c.String("query"), c.String("output"))
				},
			},
			w,
		),
	}
}

func opServersGetV1ServersByNamespaceBySlug(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "get-v1-servers-by-namespace-by-slug",
		Usage:     "Retrieve the MCP server details by its unique identifier.",
		ArgsUsage: "<namespace> <slug>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.glama.servers.get-v1-servers-by-namespace-by-slug",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("glama: need 2 positional args (namespace slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/v1/servers/" + p0 + "/" + p1
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, false, c.String("query"), c.String("output"))
				},
			},
			w,
		),
	}
}

func opTelemetryPostV1TelemetryUsage(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "post-v1-telemetry-usage",
		Usage: "Send MCP tool usage data to the server.",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.glama.telemetry.post-v1-telemetry-usage",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					path := "/v1/telemetry/usage"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "POST", path, q, body, false, c.String("query"), c.String("output"))
				},
			},
			w,
		),
	}
}

// readBody resolves the --body flag: literal JSON, '@path' for file,
// '-' for stdin. Empty input returns nil.
func readBody(spec string) ([]byte, error) {
	switch {
	case spec == "":
		return nil, nil
	case spec == "-":
		b, err := io.ReadAll(os.Stdin)
		if err != nil {
			return nil, fmt.Errorf("glama: read stdin: %w", err)
		}
		return b, nil
	case strings.HasPrefix(spec, "@"):
		b, err := os.ReadFile(spec[1:])
		if err != nil {
			return nil, fmt.Errorf("glama: read %s: %w", spec[1:], err)
		}
		return b, nil
	default:
		return []byte(spec), nil
	}
}

func doRequestAndStream(ctx context.Context, r *shell.Runner, method, path string, q url.Values, body []byte, authNeeded bool, projection, output string) error {
	target := apiBase + path
	if len(q) > 0 {
		target += "?" + q.Encode()
	}
	var rdr io.Reader
	if len(body) > 0 {
		rdr = bytes.NewReader(body)
	}
	req, err := http.NewRequestWithContext(ctx, method, target, rdr)
	if err != nil {
		return fmt.Errorf("glama: build request: %w", err)
	}
	if len(body) > 0 {
		req.Header.Set("Content-Type", "application/json")
	}
	req.Header.Set("Accept", "application/json")
	if authNeeded {
		key, err := fetchSSM(ctx, r, ssmAPIKey)
		if err != nil {
			return err
		}
		req.Header.Set("Authorization", "Bearer "+key)
	}

	client := &http.Client{Timeout: httpTimeout}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("glama: request: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("glama: read response: %w", err)
	}
	if resp.StatusCode >= 400 {
		return fmt.Errorf("glama: HTTP %d: %s", resp.StatusCode, strings.TrimSpace(string(raw)))
	}
	if len(bytes.TrimSpace(raw)) == 0 {
		return nil
	}
	outFmt, outSet, err := restfmt.ParseOutput(output)
	if err != nil {
		return err
	}
	if restfmt.NeedsRender(projection, outSet) {
		// --query alone defaults to JSON, preserving the surface's existing
		// output format; --output flips it to yaml/text. Either routes through
		// restfmt instead of the byte-identical pretty-print path below.
		if !outSet {
			outFmt = restfmt.OutputJSON
		}
		rendered, rErr := restfmt.Render(projection, outFmt, raw)
		if rErr != nil {
			return rErr
		}
		_, err = os.Stdout.Write(rendered)
		return err
	}
	var pretty json.RawMessage
	if err := json.Unmarshal(raw, &pretty); err != nil {
		_, _ = os.Stdout.Write(raw)
		return nil
	}
	out, err := json.MarshalIndent(pretty, "", "  ")
	if err != nil {
		return fmt.Errorf("glama: re-encode response: %w", err)
	}
	if _, err := fmt.Fprintln(os.Stdout, string(out)); err != nil {
		return err
	}
	return nil
}

func fetchSSM(ctx context.Context, r *shell.Runner, name string) (string, error) {
	out, err := r.Capture(ctx, "aws",
		"ssm", "get-parameter",
		"--name", name,
		"--with-decryption",
		"--query", "Parameter.Value",
		"--output", "text",
	)
	if err != nil {
		return "", fmt.Errorf("glama: fetch %s: %w", name, err)
	}
	v := strings.TrimSpace(string(out))
	if v == "" {
		return "", fmt.Errorf("glama: %s resolved to empty value", name)
	}
	return v, nil
}
