// Code generated by cmd/gen-passthrough. DO NOT EDIT.
//
// Regenerate with: go run ./cmd/gen-passthrough tailscale
// Or in bulk:      make gen-passthrough

package tailscale

import (
	"context"
	"strconv"

	"github.com/coilysiren/coily/pkg/audit"
	"github.com/coilysiren/coily/pkg/shell"
	"github.com/coilysiren/coily/pkg/verb"
	"github.com/urfave/cli/v3"
)

// BinaryName is the underlying CLI this package mirrors.
const BinaryName = "tailscale"

// Command returns the *cli.Command tree that mirrors the upstream CLI.
// Every leaf is wrapped through verb.Wrap so argv validation and audit
// logging apply uniformly.
func Command(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  BinaryName,
		Usage: "Pass-through to " + BinaryName + ".",
		Commands: []*cli.Command{
			&cli.Command{
				Name:  "cert",
				Usage: "Get TLS certs",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "cert-file"},
					&cli.StringFlag{Name: "key-file"},
					&cli.StringFlag{Name: "min-validity"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.cert",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--cert-file"] = c.String("cert-file")
							args["--key-file"] = c.String("key-file")
							args["--min-validity"] = c.String("min-validity")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"cert"}
							if c.IsSet("cert-file") {
								argv = append(argv, "--cert-file", c.String("cert-file"))
							}
							if c.IsSet("key-file") {
								argv = append(argv, "--key-file", c.String("key-file"))
							}
							if c.IsSet("min-validity") {
								argv = append(argv, "--min-validity", c.String("min-validity"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "down",
				Usage: "Disconnect from Tailscale",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "accept-risk"},
					&cli.StringFlag{Name: "reason"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.down",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--accept-risk"] = c.String("accept-risk")
							args["--reason"] = c.String("reason")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"down"}
							if c.IsSet("accept-risk") {
								argv = append(argv, "--accept-risk", c.String("accept-risk"))
							}
							if c.IsSet("reason") {
								argv = append(argv, "--reason", c.String("reason"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "funnel",
				Usage: "Serve content and local servers on the internet",
				Commands: []*cli.Command{
					&cli.Command{
						Name:  "reset",
						Usage: "Reset current funnel config",
						Action: verb.Wrap(
							verb.Spec{
								Name: "tailscale.funnel.reset",
								ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
									args := map[string]string{}
									var positional []string
									_ = positional
									positional = append(positional, c.Args().Slice()...)
									return args, positional
								},
								Action: func(ctx context.Context, c *cli.Command) error {
									argv := []string{"funnel", "reset"}
									// Forward any trailing positional args after flags so verbs
									// like "gh api <endpoint>", "kubectl get <resource>", and
									// "aws s3 cp <src> <dst>" reach the underlying tool.
									argv = append(argv, c.Args().Slice()...)
									_ = strconv.Itoa // keep strconv imported even when no flags
									return r.Exec(ctx, BinaryName, argv...)
								},
							},
							w,
						),
					},
					&cli.Command{
						Name:  "status",
						Usage: "View current funnel configuration",
						Flags: []cli.Flag{
							&cli.StringFlag{Name: "json"},
						},
						Action: verb.Wrap(
							verb.Spec{
								Name: "tailscale.funnel.status",
								ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
									args := map[string]string{}
									var positional []string
									_ = positional
									args["--json"] = c.String("json")
									positional = append(positional, c.Args().Slice()...)
									return args, positional
								},
								Action: func(ctx context.Context, c *cli.Command) error {
									argv := []string{"funnel", "status"}
									if c.IsSet("json") {
										argv = append(argv, "--json", c.String("json"))
									}
									// Forward any trailing positional args after flags so verbs
									// like "gh api <endpoint>", "kubectl get <resource>", and
									// "aws s3 cp <src> <dst>" reach the underlying tool.
									argv = append(argv, c.Args().Slice()...)
									_ = strconv.Itoa // keep strconv imported even when no flags
									return r.Exec(ctx, BinaryName, argv...)
								},
							},
							w,
						),
					},
				},
			},
			&cli.Command{
				Name:  "ip",
				Usage: "Show Tailscale IP addresses",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "assert"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.ip",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--assert"] = c.String("assert")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"ip"}
							if c.IsSet("assert") {
								argv = append(argv, "--assert", c.String("assert"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "login",
				Usage: "Log in to a Tailscale account",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "advertise-routes"},
					&cli.StringFlag{Name: "advertise-tags"},
					&cli.StringFlag{Name: "audience"},
					&cli.StringFlag{Name: "auth-key"},
					&cli.StringFlag{Name: "client-id"},
					&cli.StringFlag{Name: "client-secret"},
					&cli.StringFlag{Name: "exit-node"},
					&cli.StringFlag{Name: "hostname"},
					&cli.StringFlag{Name: "id-token"},
					&cli.StringFlag{Name: "login-server"},
					&cli.StringFlag{Name: "nickname"},
					&cli.StringFlag{Name: "qr-format"},
					&cli.StringFlag{Name: "timeout"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.login",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--advertise-routes"] = c.String("advertise-routes")
							args["--advertise-tags"] = c.String("advertise-tags")
							args["--audience"] = c.String("audience")
							args["--auth-key"] = c.String("auth-key")
							args["--client-id"] = c.String("client-id")
							args["--client-secret"] = c.String("client-secret")
							args["--exit-node"] = c.String("exit-node")
							args["--hostname"] = c.String("hostname")
							args["--id-token"] = c.String("id-token")
							args["--login-server"] = c.String("login-server")
							args["--nickname"] = c.String("nickname")
							args["--qr-format"] = c.String("qr-format")
							args["--timeout"] = c.String("timeout")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"login"}
							if c.IsSet("advertise-routes") {
								argv = append(argv, "--advertise-routes", c.String("advertise-routes"))
							}
							if c.IsSet("advertise-tags") {
								argv = append(argv, "--advertise-tags", c.String("advertise-tags"))
							}
							if c.IsSet("audience") {
								argv = append(argv, "--audience", c.String("audience"))
							}
							if c.IsSet("auth-key") {
								argv = append(argv, "--auth-key", c.String("auth-key"))
							}
							if c.IsSet("client-id") {
								argv = append(argv, "--client-id", c.String("client-id"))
							}
							if c.IsSet("client-secret") {
								argv = append(argv, "--client-secret", c.String("client-secret"))
							}
							if c.IsSet("exit-node") {
								argv = append(argv, "--exit-node", c.String("exit-node"))
							}
							if c.IsSet("hostname") {
								argv = append(argv, "--hostname", c.String("hostname"))
							}
							if c.IsSet("id-token") {
								argv = append(argv, "--id-token", c.String("id-token"))
							}
							if c.IsSet("login-server") {
								argv = append(argv, "--login-server", c.String("login-server"))
							}
							if c.IsSet("nickname") {
								argv = append(argv, "--nickname", c.String("nickname"))
							}
							if c.IsSet("qr-format") {
								argv = append(argv, "--qr-format", c.String("qr-format"))
							}
							if c.IsSet("timeout") {
								argv = append(argv, "--timeout", c.String("timeout"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "logout",
				Usage: "Disconnect from Tailscale and expire current node key",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "reason"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.logout",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--reason"] = c.String("reason")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"logout"}
							if c.IsSet("reason") {
								argv = append(argv, "--reason", c.String("reason"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "netcheck",
				Usage: "Print an analysis of local network conditions",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "bind-address"},
					&cli.StringFlag{Name: "bind-port"},
					&cli.StringFlag{Name: "every"},
					&cli.StringFlag{Name: "format"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.netcheck",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--bind-address"] = c.String("bind-address")
							args["--bind-port"] = c.String("bind-port")
							args["--every"] = c.String("every")
							args["--format"] = c.String("format")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"netcheck"}
							if c.IsSet("bind-address") {
								argv = append(argv, "--bind-address", c.String("bind-address"))
							}
							if c.IsSet("bind-port") {
								argv = append(argv, "--bind-port", c.String("bind-port"))
							}
							if c.IsSet("every") {
								argv = append(argv, "--every", c.String("every"))
							}
							if c.IsSet("format") {
								argv = append(argv, "--format", c.String("format"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "ping",
				Usage: "Ping a host at the Tailscale layer, see how it routed",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "c"},
					&cli.StringFlag{Name: "size"},
					&cli.StringFlag{Name: "timeout"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.ping",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--c"] = c.String("c")
							args["--size"] = c.String("size")
							args["--timeout"] = c.String("timeout")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"ping"}
							if c.IsSet("c") {
								argv = append(argv, "--c", c.String("c"))
							}
							if c.IsSet("size") {
								argv = append(argv, "--size", c.String("size"))
							}
							if c.IsSet("timeout") {
								argv = append(argv, "--timeout", c.String("timeout"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "serve",
				Usage: "Serve content and local servers on your tailnet",
				Commands: []*cli.Command{
					&cli.Command{
						Name:  "advertise",
						Usage: "Advertise this node as a service proxy to the tailnet",
						Action: verb.Wrap(
							verb.Spec{
								Name: "tailscale.serve.advertise",
								ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
									args := map[string]string{}
									var positional []string
									_ = positional
									positional = append(positional, c.Args().Slice()...)
									return args, positional
								},
								Action: func(ctx context.Context, c *cli.Command) error {
									argv := []string{"serve", "advertise"}
									// Forward any trailing positional args after flags so verbs
									// like "gh api <endpoint>", "kubectl get <resource>", and
									// "aws s3 cp <src> <dst>" reach the underlying tool.
									argv = append(argv, c.Args().Slice()...)
									_ = strconv.Itoa // keep strconv imported even when no flags
									return r.Exec(ctx, BinaryName, argv...)
								},
							},
							w,
						),
					},
					&cli.Command{
						Name:  "clear",
						Usage: "Remove all config for a service",
						Action: verb.Wrap(
							verb.Spec{
								Name: "tailscale.serve.clear",
								ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
									args := map[string]string{}
									var positional []string
									_ = positional
									positional = append(positional, c.Args().Slice()...)
									return args, positional
								},
								Action: func(ctx context.Context, c *cli.Command) error {
									argv := []string{"serve", "clear"}
									// Forward any trailing positional args after flags so verbs
									// like "gh api <endpoint>", "kubectl get <resource>", and
									// "aws s3 cp <src> <dst>" reach the underlying tool.
									argv = append(argv, c.Args().Slice()...)
									_ = strconv.Itoa // keep strconv imported even when no flags
									return r.Exec(ctx, BinaryName, argv...)
								},
							},
							w,
						),
					},
					&cli.Command{
						Name:  "drain",
						Usage: "Drain a service from the current node",
						Action: verb.Wrap(
							verb.Spec{
								Name: "tailscale.serve.drain",
								ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
									args := map[string]string{}
									var positional []string
									_ = positional
									positional = append(positional, c.Args().Slice()...)
									return args, positional
								},
								Action: func(ctx context.Context, c *cli.Command) error {
									argv := []string{"serve", "drain"}
									// Forward any trailing positional args after flags so verbs
									// like "gh api <endpoint>", "kubectl get <resource>", and
									// "aws s3 cp <src> <dst>" reach the underlying tool.
									argv = append(argv, c.Args().Slice()...)
									_ = strconv.Itoa // keep strconv imported even when no flags
									return r.Exec(ctx, BinaryName, argv...)
								},
							},
							w,
						),
					},
					&cli.Command{
						Name:  "get-config",
						Usage: "Get service configuration to save to a file",
						Flags: []cli.Flag{
							&cli.StringFlag{Name: "service"},
						},
						Action: verb.Wrap(
							verb.Spec{
								Name: "tailscale.serve.get-config",
								ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
									args := map[string]string{}
									var positional []string
									_ = positional
									args["--service"] = c.String("service")
									positional = append(positional, c.Args().Slice()...)
									return args, positional
								},
								Action: func(ctx context.Context, c *cli.Command) error {
									argv := []string{"serve", "get-config"}
									if c.IsSet("service") {
										argv = append(argv, "--service", c.String("service"))
									}
									// Forward any trailing positional args after flags so verbs
									// like "gh api <endpoint>", "kubectl get <resource>", and
									// "aws s3 cp <src> <dst>" reach the underlying tool.
									argv = append(argv, c.Args().Slice()...)
									_ = strconv.Itoa // keep strconv imported even when no flags
									return r.Exec(ctx, BinaryName, argv...)
								},
							},
							w,
						),
					},
					&cli.Command{
						Name:  "reset",
						Usage: "Reset current serve config",
						Action: verb.Wrap(
							verb.Spec{
								Name: "tailscale.serve.reset",
								ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
									args := map[string]string{}
									var positional []string
									_ = positional
									positional = append(positional, c.Args().Slice()...)
									return args, positional
								},
								Action: func(ctx context.Context, c *cli.Command) error {
									argv := []string{"serve", "reset"}
									// Forward any trailing positional args after flags so verbs
									// like "gh api <endpoint>", "kubectl get <resource>", and
									// "aws s3 cp <src> <dst>" reach the underlying tool.
									argv = append(argv, c.Args().Slice()...)
									_ = strconv.Itoa // keep strconv imported even when no flags
									return r.Exec(ctx, BinaryName, argv...)
								},
							},
							w,
						),
					},
					&cli.Command{
						Name:  "set-config",
						Usage: "Define service configuration from a file",
						Flags: []cli.Flag{
							&cli.StringFlag{Name: "service"},
						},
						Action: verb.Wrap(
							verb.Spec{
								Name: "tailscale.serve.set-config",
								ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
									args := map[string]string{}
									var positional []string
									_ = positional
									args["--service"] = c.String("service")
									positional = append(positional, c.Args().Slice()...)
									return args, positional
								},
								Action: func(ctx context.Context, c *cli.Command) error {
									argv := []string{"serve", "set-config"}
									if c.IsSet("service") {
										argv = append(argv, "--service", c.String("service"))
									}
									// Forward any trailing positional args after flags so verbs
									// like "gh api <endpoint>", "kubectl get <resource>", and
									// "aws s3 cp <src> <dst>" reach the underlying tool.
									argv = append(argv, c.Args().Slice()...)
									_ = strconv.Itoa // keep strconv imported even when no flags
									return r.Exec(ctx, BinaryName, argv...)
								},
							},
							w,
						),
					},
					&cli.Command{
						Name:  "status",
						Usage: "View current serve configuration",
						Flags: []cli.Flag{
							&cli.StringFlag{Name: "json"},
						},
						Action: verb.Wrap(
							verb.Spec{
								Name: "tailscale.serve.status",
								ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
									args := map[string]string{}
									var positional []string
									_ = positional
									args["--json"] = c.String("json")
									positional = append(positional, c.Args().Slice()...)
									return args, positional
								},
								Action: func(ctx context.Context, c *cli.Command) error {
									argv := []string{"serve", "status"}
									if c.IsSet("json") {
										argv = append(argv, "--json", c.String("json"))
									}
									// Forward any trailing positional args after flags so verbs
									// like "gh api <endpoint>", "kubectl get <resource>", and
									// "aws s3 cp <src> <dst>" reach the underlying tool.
									argv = append(argv, c.Args().Slice()...)
									_ = strconv.Itoa // keep strconv imported even when no flags
									return r.Exec(ctx, BinaryName, argv...)
								},
							},
							w,
						),
					},
				},
			},
			&cli.Command{
				Name:  "set",
				Usage: "Change specified preferences",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "accept-risk"},
					&cli.StringFlag{Name: "advertise-routes"},
					&cli.StringFlag{Name: "exit-node"},
					&cli.StringFlag{Name: "hostname"},
					&cli.StringFlag{Name: "nickname"},
					&cli.StringFlag{Name: "relay-server-port"},
					&cli.StringFlag{Name: "relay-server-static-endpoints"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.set",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--accept-risk"] = c.String("accept-risk")
							args["--advertise-routes"] = c.String("advertise-routes")
							args["--exit-node"] = c.String("exit-node")
							args["--hostname"] = c.String("hostname")
							args["--nickname"] = c.String("nickname")
							args["--relay-server-port"] = c.String("relay-server-port")
							args["--relay-server-static-endpoints"] = c.String("relay-server-static-endpoints")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"set"}
							if c.IsSet("accept-risk") {
								argv = append(argv, "--accept-risk", c.String("accept-risk"))
							}
							if c.IsSet("advertise-routes") {
								argv = append(argv, "--advertise-routes", c.String("advertise-routes"))
							}
							if c.IsSet("exit-node") {
								argv = append(argv, "--exit-node", c.String("exit-node"))
							}
							if c.IsSet("hostname") {
								argv = append(argv, "--hostname", c.String("hostname"))
							}
							if c.IsSet("nickname") {
								argv = append(argv, "--nickname", c.String("nickname"))
							}
							if c.IsSet("relay-server-port") {
								argv = append(argv, "--relay-server-port", c.String("relay-server-port"))
							}
							if c.IsSet("relay-server-static-endpoints") {
								argv = append(argv, "--relay-server-static-endpoints", c.String("relay-server-static-endpoints"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "ssh",
				Usage: "SSH to a Tailscale machine",
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.ssh",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"ssh"}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "status",
				Usage: "Show state of tailscaled and its connections",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "listen"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.status",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--listen"] = c.String("listen")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"status"}
							if c.IsSet("listen") {
								argv = append(argv, "--listen", c.String("listen"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "switch",
				Usage: "Switch to a different Tailscale account",
				Commands: []*cli.Command{
					&cli.Command{
						Name:  "remove",
						Usage: "Remove a Tailscale account",
						Action: verb.Wrap(
							verb.Spec{
								Name: "tailscale.switch.remove",
								ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
									args := map[string]string{}
									var positional []string
									_ = positional
									positional = append(positional, c.Args().Slice()...)
									return args, positional
								},
								Action: func(ctx context.Context, c *cli.Command) error {
									argv := []string{"switch", "remove"}
									// Forward any trailing positional args after flags so verbs
									// like "gh api <endpoint>", "kubectl get <resource>", and
									// "aws s3 cp <src> <dst>" reach the underlying tool.
									argv = append(argv, c.Args().Slice()...)
									_ = strconv.Itoa // keep strconv imported even when no flags
									return r.Exec(ctx, BinaryName, argv...)
								},
							},
							w,
						),
					},
				},
			},
			&cli.Command{
				Name:  "up",
				Usage: "Connect to Tailscale, logging in if needed",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "accept-risk"},
					&cli.StringFlag{Name: "advertise-routes"},
					&cli.StringFlag{Name: "advertise-tags"},
					&cli.StringFlag{Name: "audience"},
					&cli.StringFlag{Name: "auth-key"},
					&cli.StringFlag{Name: "client-id"},
					&cli.StringFlag{Name: "client-secret"},
					&cli.StringFlag{Name: "exit-node"},
					&cli.StringFlag{Name: "hostname"},
					&cli.StringFlag{Name: "id-token"},
					&cli.StringFlag{Name: "login-server"},
					&cli.StringFlag{Name: "qr-format"},
					&cli.StringFlag{Name: "timeout"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.up",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--accept-risk"] = c.String("accept-risk")
							args["--advertise-routes"] = c.String("advertise-routes")
							args["--advertise-tags"] = c.String("advertise-tags")
							args["--audience"] = c.String("audience")
							args["--auth-key"] = c.String("auth-key")
							args["--client-id"] = c.String("client-id")
							args["--client-secret"] = c.String("client-secret")
							args["--exit-node"] = c.String("exit-node")
							args["--hostname"] = c.String("hostname")
							args["--id-token"] = c.String("id-token")
							args["--login-server"] = c.String("login-server")
							args["--qr-format"] = c.String("qr-format")
							args["--timeout"] = c.String("timeout")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"up"}
							if c.IsSet("accept-risk") {
								argv = append(argv, "--accept-risk", c.String("accept-risk"))
							}
							if c.IsSet("advertise-routes") {
								argv = append(argv, "--advertise-routes", c.String("advertise-routes"))
							}
							if c.IsSet("advertise-tags") {
								argv = append(argv, "--advertise-tags", c.String("advertise-tags"))
							}
							if c.IsSet("audience") {
								argv = append(argv, "--audience", c.String("audience"))
							}
							if c.IsSet("auth-key") {
								argv = append(argv, "--auth-key", c.String("auth-key"))
							}
							if c.IsSet("client-id") {
								argv = append(argv, "--client-id", c.String("client-id"))
							}
							if c.IsSet("client-secret") {
								argv = append(argv, "--client-secret", c.String("client-secret"))
							}
							if c.IsSet("exit-node") {
								argv = append(argv, "--exit-node", c.String("exit-node"))
							}
							if c.IsSet("hostname") {
								argv = append(argv, "--hostname", c.String("hostname"))
							}
							if c.IsSet("id-token") {
								argv = append(argv, "--id-token", c.String("id-token"))
							}
							if c.IsSet("login-server") {
								argv = append(argv, "--login-server", c.String("login-server"))
							}
							if c.IsSet("qr-format") {
								argv = append(argv, "--qr-format", c.String("qr-format"))
							}
							if c.IsSet("timeout") {
								argv = append(argv, "--timeout", c.String("timeout"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "update",
				Usage: "Update Tailscale to the latest/different version",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "track"},
					&cli.StringFlag{Name: "version"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.update",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--track"] = c.String("track")
							args["--version"] = c.String("version")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"update"}
							if c.IsSet("track") {
								argv = append(argv, "--track", c.String("track"))
							}
							if c.IsSet("version") {
								argv = append(argv, "--version", c.String("version"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
			&cli.Command{
				Name:  "whois",
				Usage: "Show the machine and user associated with a Tailscale IP (v4 or v6)",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "proto"},
				},
				Action: verb.Wrap(
					verb.Spec{
						Name: "tailscale.whois",
						ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
							args := map[string]string{}
							var positional []string
							_ = positional
							args["--proto"] = c.String("proto")
							positional = append(positional, c.Args().Slice()...)
							return args, positional
						},
						Action: func(ctx context.Context, c *cli.Command) error {
							argv := []string{"whois"}
							if c.IsSet("proto") {
								argv = append(argv, "--proto", c.String("proto"))
							}
							// Forward any trailing positional args after flags so verbs
							// like "gh api <endpoint>", "kubectl get <resource>", and
							// "aws s3 cp <src> <dst>" reach the underlying tool.
							argv = append(argv, c.Args().Slice()...)
							_ = strconv.Itoa // keep strconv imported even when no flags
							return r.Exec(ctx, BinaryName, argv...)
						},
					},
					w,
				),
			},
		},
	}
}
