package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/cli/decision"
	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/cli/lockdown"
	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/pkg/config"
)

// coilyAllowedPaths is the closed set of filesystem paths a `coily`
// invocation is permitted to resolve to. Anything else (including
// ~/go/bin/coily, /tmp/foo/coily, ./bin/coily) is rejected by the
// generated PreToolUse hook. The list covers homebrew on Apple
// Silicon, homebrew on Intel macOS, and Linuxbrew on Linux
// (kai-server). The hook follows the bin/coily symlink Brew lays
// down rather than the Cellar realpath, because `command -v coily`
// returns the symlink path.
var coilyAllowedPaths = []string{
	"/opt/homebrew/bin/coily",              // Apple Silicon homebrew
	"/usr/local/bin/coily",                 // Intel macOS homebrew
	"/home/linuxbrew/.linuxbrew/bin/coily", // Linuxbrew default prefix
}

// wrapperRecovery (the bare-binary -> coily-wrapper recovery map) is now
// generated in wrapper_recovery.go from the passthrough registries, so it
// tracks what coily actually fronts. Issues #61, #122, #197.

// coilyRenderHookScript is the per-repo PreToolUse hook body written by
// `coily lockdown`. Delegates to `coily hook pre-tool-use`, which calls
// the shared cli-guard/hook engine with coily's own integrity rules and
// routing-hint Route table. Per coilysiren/coily#248 + cli-guard#74:
// the cross-consumer reference (a legacy shim into a peer consumer's
// hook) is gone; coily and ward are peer cli-guard consumers that do
// not name each other in source.
func coilyRenderHookScript(_ *lockdown.Defaults, _ *lockdown.Driver) (string, error) {
	return "#!/bin/sh\n" +
		"# Auto-generated by coily. Regenerate via coily lockdown --apply --replace.\n" +
		"# Delegates to coily hook pre-tool-use (cli-guard engine).\n" +
		"exec coily hook pre-tool-use\n", nil
}

// coilySessionStartHookCommand is the settings.json hook command coily
// lockdown installs under SessionStart. Emits the capability index
// (surface map + presence!=auth doctrine) so every session in a
// locked-down repo opens knowing what coily fronts. coilyco-bridge/coily#197.
const coilySessionStartHookCommand = "coily hook session-start"

// injectSessionStartHook adds the coily SessionStart capability-index hook
// to a settings.json blob already built by cli-guard's BuildSettings (which
// installs the PreToolUse Bash hook). Idempotent: a settings file that
// already names the command is returned unchanged in content. Preserves the
// two-space indent + trailing newline cli-guard writes so regeneration stays
// diff-clean.
func injectSessionStartHook(b []byte) ([]byte, error) {
	var out map[string]any
	if len(b) > 0 {
		if err := json.Unmarshal(b, &out); err != nil {
			return nil, fmt.Errorf("coily lockdown: parse settings for SessionStart hook: %w", err)
		}
	}
	if out == nil {
		out = map[string]any{}
	}
	hooks, _ := out["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
		out["hooks"] = hooks
	}
	entries, _ := hooks["SessionStart"].([]any)
	if !sessionStartHookPresent(entries) {
		entries = append(entries, map[string]any{
			"hooks": []any{
				map[string]any{"type": "command", "command": coilySessionStartHookCommand},
			},
		})
		hooks["SessionStart"] = entries
	}
	encoded, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("coily lockdown: marshal settings with SessionStart hook: %w", err)
	}
	return append(encoded, '\n'), nil
}

// sessionStartHookPresent reports whether any SessionStart entry already
// installs the coily capability-index command, so regeneration does not
// stack duplicate entries.
func sessionStartHookPresent(entries []any) bool {
	for _, e := range entries {
		em, ok := e.(map[string]any)
		if !ok {
			continue
		}
		hs, ok := em["hooks"].([]any)
		if !ok {
			continue
		}
		for _, h := range hs {
			hm, ok := h.(map[string]any)
			if !ok {
				continue
			}
			if cmd, _ := hm["command"].(string); cmd == coilySessionStartHookCommand {
				return true
			}
		}
	}
	return false
}

// coilyLockdownDriver returns the ClaudeCode-shaped lockdown driver
// for the coily binary. Called wherever the lockdown writer needs to
// know which binary it is gating and which wrappers to mention in
// deny recovery hints.
func coilyLockdownDriver() *lockdown.Driver {
	drv := lockdown.ClaudeCode("coily", coilyAllowedPaths, wrapperRecovery)
	drv.RenderHookScript = coilyRenderHookScript
	// Wrap cli-guard's BuildSettings to also install the SessionStart
	// capability-index hook (coilyco-bridge/coily#197). cli-guard owns the
	// PreToolUse half; coily layers awareness on top without forking it.
	baseBuild := drv.BuildSettings
	drv.BuildSettings = func(existing []byte, d *lockdown.Defaults, dr *lockdown.Driver) ([]byte, error) {
		out, err := baseBuild(existing, d, dr)
		if err != nil {
			return nil, err
		}
		return injectSessionStartHook(out)
	}
	// Phase 4 plumbing for #150: attach the resolved per-session
	// Coordinate to the driver so phase 5's BuildSettings consumer can
	// branch on it. Best-effort: a malformed override file leaves the
	// Coordinate unset (nil) so today's settings.json output path is
	// unaffected.
	sid := strings.TrimSpace(os.Getenv(sessionEnvVar))
	if sid != "" {
		if active, err := readSessionProfileName(sid); err == nil {
			if c, err := decision.CoordinatePtr(active); err == nil {
				drv.Coordinate = c
			}
		}
	}
	return drv
}

// readSessionProfileName reads the session sentinel for sid via the
// same code path as `coily session show`, returning the empty string
// if the sentinel is absent. Errors propagate only for malformed
// sentinels.
func readSessionProfileName(sid string) (string, error) {
	path, err := config.SessionProfilePath(sid)
	if err != nil {
		return "", err
	}
	b, err := os.ReadFile(path) //nolint:gosec // path derived from $CLAUDE_CODE_SESSION_ID via config.SessionProfilePath
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return strings.TrimSpace(string(b)), nil
}
