package main

import (
	"forgejo.coilysiren.me/coilyco-bridge/coily/cmd/coily/trello"
	"github.com/urfave/cli/v3"
)

// trelloCommand mounts the generated Trello REST wrapper under
// `coily ops trello`. Generated by scripts/openapi-to-coily.py from
// the Atlassian Trello Swagger spec.
func (r *Runner) trelloCommand() *cli.Command {
	return trello.Command(r.Runner, r.Audit)
}
