package main

import (
	"forgejo.coilysiren.me/coilyco-bridge/coily/cmd/coily/trello"
	"github.com/urfave/cli/v3"
)

// trelloCommand mounts the generated Trello REST wrapper under
// `coily ops trello`. Generated by scripts/openapi-to-coily.py from the
// Atlassian Trello Swagger spec. The coily-side --query/--output projection
// rail (coilyco-bridge/coily#46) is folded into the generator itself now, so
// every leaf inherits the persistent --query/--output flags (and --jq on the
// search ops that own an API --query) with no hand-written wrapper - the old
// os.Stdout-capture shim is gone (coilyco-bridge/coily#182).
func (r *Runner) trelloCommand() *cli.Command {
	return trello.Command(r.Runner, r.Audit)
}
