package main

import (
	"bytes"
	"context"
	"io"
	"os"

	"forgejo.coilysiren.me/coilyco-bridge/coily/cmd/coily/restfmt"
	"forgejo.coilysiren.me/coilyco-bridge/coily/cmd/coily/trello"
	"github.com/urfave/cli/v3"
)

// trelloCommand mounts the generated Trello REST wrapper under
// `coily ops trello`. Generated by scripts/openapi-to-coily.py from the
// Atlassian Trello Swagger spec, then wrapped here with coily-side
// --query/--output (coilyco-bridge/coily#46) so a response can be projected
// with JMESPath and re-rendered without an ad-hoc jq/python pipe.
func (r *Runner) trelloCommand() *cli.Command {
	cmd := trello.Command(r.Runner, r.Audit)
	addQueryOutput(cmd)
	return cmd
}

// addQueryOutput recursively wires coily-side --query/--output onto every leaf
// op of a generated REST surface. Leaf ops keep byte-for-byte identical output
// when neither flag is set. A flag is skipped on any op that already declares a
// same-named API parameter (the Trello search ops own --query), so those few
// keep their native semantics; coily projection on them is a follow-up.
//
// This wrapper lives in hand-written code rather than the generator so the MVP
// (coily#46) ships against one surface without regenerating the whole tree;
// the durable form folds this into scripts/openapi-to-coily.py for every
// surface as a follow-up.
func addQueryOutput(cmd *cli.Command) {
	if len(cmd.Commands) > 0 {
		for _, sub := range cmd.Commands {
			addQueryOutput(sub)
		}
		return
	}
	if cmd.Action == nil {
		return
	}
	if !hasFlag(cmd, "query") {
		cmd.Flags = append(cmd.Flags, &cli.StringFlag{
			Name:  "query",
			Usage: "JMESPath projection applied to the JSON response (coily#46)",
		})
	}
	if !hasFlag(cmd, "output") {
		cmd.Flags = append(cmd.Flags, &cli.StringFlag{
			Name:  "output",
			Usage: "output format: json (default), yaml, text (coily#46)",
		})
	}
	cmd.Action = wrapQueryOutput(cmd.Action)
}

func hasFlag(cmd *cli.Command, name string) bool {
	for _, f := range cmd.Flags {
		for _, n := range f.Names() {
			if n == name {
				return true
			}
		}
	}
	return false
}

// wrapQueryOutput intercepts --query/--output around a generated leaf action.
// When neither is set it delegates untouched. Otherwise it captures the
// action's stdout (the generated doRequestAndStream prints the JSON response
// there), applies the JMESPath projection + formatter, and writes the result.
func wrapQueryOutput(inner cli.ActionFunc) cli.ActionFunc {
	return func(ctx context.Context, c *cli.Command) error {
		query := c.String("query")
		out, outSet, err := restfmt.ParseOutput(c.String("output"))
		if err != nil {
			return err
		}
		if !restfmt.NeedsRender(query, outSet) {
			return inner(ctx, c)
		}
		if !outSet {
			// --query alone defaults to JSON, preserving the surface's
			// existing output format. The yaml-default flip in coily#46 is a
			// deliberate follow-up policy change, tracked separately.
			out = restfmt.OutputJSON
		}

		captured, runErr := captureStdout(func() error { return inner(ctx, c) })
		if runErr != nil {
			return runErr
		}
		if len(bytes.TrimSpace(captured)) == 0 {
			return nil
		}
		rendered, rErr := restfmt.Render(query, out, captured)
		if rErr != nil {
			return rErr
		}
		_, err = os.Stdout.Write(rendered)
		return err
	}
}

// captureStdout redirects os.Stdout for the duration of fn and returns what fn
// wrote. coily runs a single verb per process, so the global swap is safe; a
// goroutine drains the pipe to avoid blocking on a large response.
func captureStdout(fn func() error) ([]byte, error) {
	orig := os.Stdout
	rp, wp, err := os.Pipe()
	if err != nil {
		return nil, err
	}
	os.Stdout = wp
	done := make(chan []byte, 1)
	go func() {
		var buf bytes.Buffer
		_, _ = io.Copy(&buf, rp)
		done <- buf.Bytes()
	}()

	runErr := fn()

	_ = wp.Close()
	os.Stdout = orig
	captured := <-done
	_ = rp.Close()
	return captured, runErr
}
