package main

import (
	"github.com/coilysiren/coily/cmd/coily/glama"
	"github.com/urfave/cli/v3"
)

// glamaCommand mounts the Glama wrapper under `coily pkg glama`. The
// package itself is generated by scripts/openapi-to-coily.py.
func (r *Runner) glamaCommand() *cli.Command {
	return glama.Command(r.Runner, r.Audit)
}
