#!/usr/bin/env python3
"""
One-shot migration: walk every coily-*-meta/findings/*.md in the old
skill spread, file each as a GitHub issue on coilysiren/coily with label
`finding`, and write a mapping file at coily-meta/findings-migration.md.

Ran on 2026-05-17 as part of coilysiren/coily#215 (collapse coily-*-meta
spread, hoist findings out of the filesystem).

Idempotent only in the trivial sense: re-running files a fresh set of
issues. Kept committed as the audit trail of what happened on migration
day; do not re-run.
"""
import json
import subprocess
import sys
from pathlib import Path

SKILLS_ROOT = Path(__file__).resolve().parents[2]
REPO = "coilysiren/coily"


def find_findings():
    """yield (area, path) for every finding file in the old skill spread."""
    for meta_dir in sorted(SKILLS_ROOT.glob("coily-*/findings")):
        skill_name = meta_dir.parent.name
        # area = drop the coily- prefix and -meta suffix where present
        area = skill_name
        if area.startswith("coily-"):
            area = area[len("coily-"):]
        if area.endswith("-meta"):
            area = area[: -len("-meta")]
        for f in sorted(meta_dir.glob("*.md")):
            yield area, f


def parse_finding(path: Path):
    """Return (title, body) for an existing finding file."""
    text = path.read_text()
    # strip YAML frontmatter if present
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            text = text[end + 5 :].lstrip()
    # first markdown heading is the title source
    title_line = ""
    for line in text.splitlines():
        if line.startswith("# "):
            title_line = line[2:].strip()
            break
    if not title_line:
        title_line = path.stem
    return title_line, text


def file_issue(area: str, path: Path):
    title, body = parse_finding(path)
    prefix = f"finding ({area}): "
    full_title = prefix + title
    header = (
        f"_Migrated from `{path.relative_to(SKILLS_ROOT)}` on 2026-05-17 "
        f"as part of coilysiren/coily#215. Original file preserved in git "
        f"history; see deletion commit on coilysiren/coily#215._\n\n"
    )
    # Go through `gh api` with a JSON payload file so title + body avoid argv
    # entirely. Titles often carry parens / colons that the coily metachar
    # gate rejects on positional args. The native issue-create verb does not
    # have a --title-file option as of gh 2.x.
    payload = {
        "title": full_title,
        "body": header + body,
        "labels": ["finding"],
    }
    payload_file = Path("/tmp") / f"finding-payload-{path.stem}.json"
    payload_file.write_text(json.dumps(payload))
    result = subprocess.run(
        [
            "coily",
            "ops",
            "gh",
            "api",
            "-X",
            "POST",
            f"repos/{REPO}/issues",
            "--input",
            str(payload_file),
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)
    return data["number"], data["html_url"], full_title


def main():
    mapping = []
    for area, path in find_findings():
        rel = path.relative_to(SKILLS_ROOT)
        try:
            num, url, title = file_issue(area, path)
            mapping.append((str(rel), num, url, title))
            print(f"#{num}  {rel}", file=sys.stderr)
        except subprocess.CalledProcessError as e:
            print(f"FAIL  {rel}\n  stderr: {e.stderr}", file=sys.stderr)
            mapping.append((str(rel), None, None, f"FAILED: {e.stderr}"))

    out = SKILLS_ROOT / "coily-meta" / "findings-migration.md"
    lines = [
        "# Findings migration: 2026-05-17",
        "",
        "Mapping from the old on-disk finding files to the GitHub issues that",
        "replaced them, per coilysiren/coily#215. Generated by",
        "`scripts/migrate-findings-to-issues.py`. Source files are preserved in",
        "git history through the deletion commit on coilysiren/coily#215.",
        "",
        "| Old path | New issue |",
        "|---|---|",
    ]
    for rel, num, url, _ in mapping:
        if num is None:
            lines.append(f"| `{rel}` | FAILED |")
        else:
            lines.append(f"| `{rel}` | [#{num}]({url}) |")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"\nwrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
