// Package sentry wraps the API Reference REST API (https://us.sentry.io).
//
// Generated by scripts/openapi-to-coily.py from https://raw.githubusercontent.com/getsentry/sentry/master/api-docs/openapi.json. Do not edit
// by hand: re-run the generator. The generator emits one cli.Command per
// (path, method) tuple, grouped by OpenAPI tag. Path parameters are
// positional in declaration order; query parameters become --<name>
// string flags; request bodies arrive via --body (literal | @file | -).
// Responses stream to stdout pretty-printed (JSON) or verbatim (other).
//
// Bearer auth from AWS SSM at /sentry/api-key on every call.
package sentry

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"github.com/coilysiren/coily/pkg/audit"
	"github.com/coilysiren/coily/pkg/shell"
	"github.com/coilysiren/coily/pkg/verb"
	"github.com/urfave/cli/v3"
)

const (
	apiBase     = "https://us.sentry.io"
	httpTimeout = 60 * time.Second
	ssmAPIKey   = "/sentry/api-key" //nolint:gosec // SSM path, not a credential
)

// Command returns the cli.Command tree for `coily ops sentry`.
func Command(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "sentry",
		Usage: "Sentry Public API (bearer auth).",
		Commands: []*cli.Command{
			groupEvents(r, w),
			groupIntegration(r, w),
			groupOrganizations(r, w),
			groupProjects(r, w),
			groupReleases(r, w),
		},
	}
}

func groupEvents(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "events",
		Usage: "API Reference endpoints tagged events.",
		Commands: []*cli.Command{
			opEventsRetrieveAnEventForAProject(r, w),
			opEventsListAProjectSIssues(r, w),
			opEventsBulkMutateAListOfIssues(r, w),
			opEventsBulkRemoveAListOfIssues(r, w),
			opEventsListATagSValuesRelatedToAnIssue(r, w),
			opEventsListAnIssueSHashes(r, w),
			opEventsRetrieveAnIssue(r, w),
			opEventsUpdateAnIssue(r, w),
			opEventsRemoveAnIssue(r, w),
		},
	}
}

func groupIntegration(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "integration",
		Usage: "API Reference endpoints tagged integration.",
		Commands: []*cli.Command{
			opIntegrationListAnOrganizationSIntegrationPlatformInstallations(r, w),
			opIntegrationCreateOrUpdateAnExternalIssue(r, w),
			opIntegrationDeleteAnExternalIssue(r, w),
		},
	}
}

func groupOrganizations(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "organizations",
		Usage: "API Reference endpoints tagged organizations.",
		Commands: []*cli.Command{
			opOrganizationsListAnOrganizationSRepositories(r, w),
		},
	}
}

func groupProjects(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "projects",
		Usage: "API Reference endpoints tagged projects.",
		Commands: []*cli.Command{
			opProjectsListAProjectSDebugInformationFiles(r, w),
			opProjectsUploadANewFile(r, w),
			opProjectsDeleteASpecificProjectSDebugInformationFile(r, w),
			opProjectsListAProjectSUsers(r, w),
			opProjectsListATagSValues(r, w),
			opProjectsRetrieveEventCountsForAProject(r, w),
			opProjectsListAProjectSUserFeedback(r, w),
			opProjectsSubmitUserFeedback(r, w),
			opProjectsListAProjectSServiceHooks(r, w),
			opProjectsRegisterANewServiceHook(r, w),
			opProjectsRetrieveAServiceHook(r, w),
			opProjectsUpdateAServiceHook(r, w),
			opProjectsRemoveAServiceHook(r, w),
			opProjectsEnableSpikeProtection(r, w),
			opProjectsDisableSpikeProtection(r, w),
		},
	}
}

func groupReleases(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:  "releases",
		Usage: "API Reference endpoints tagged releases.",
		Commands: []*cli.Command{
			opReleasesListAnOrganizationSReleases(r, w),
			opReleasesCreateANewReleaseForAnOrganization(r, w),
			opReleasesListAnOrganizationSReleaseFiles(r, w),
			opReleasesUploadANewOrganizationReleaseFile(r, w),
			opReleasesListAProjectSReleaseFiles(r, w),
			opReleasesUploadANewProjectReleaseFile(r, w),
			opReleasesRetrieveAnOrganizationReleaseSFile(r, w),
			opReleasesUpdateAnOrganizationReleaseFile(r, w),
			opReleasesDeleteAnOrganizationReleaseSFile(r, w),
			opReleasesRetrieveAProjectReleaseSFile(r, w),
			opReleasesUpdateAProjectReleaseFile(r, w),
			opReleasesDeleteAProjectReleaseSFile(r, w),
			opReleasesListAnOrganizationReleaseSCommits(r, w),
			opReleasesListAProjectReleaseSCommits(r, w),
			opReleasesRetrieveFilesChangedInAReleaseSCommits(r, w),
		},
	}
}

func opEventsRetrieveAnEventForAProject(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "retrieve-an-event-for-a-project",
		Usage:     "Return details on an individual event.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug> <event_id>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.events.retrieve-an-event-for-a-project",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug project_id_or_slug event_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/events/" + p2 + "/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opEventsListAProjectSIssues(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-a-project-s-issues",
		Usage:     "**Deprecated**: This endpoint has been replaced with the [Organization Issues endpoint](/api/events/list-an-organizatio…",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "statsPeriod", Usage: "query: An optional stat period (can be one of `'24h'`, `'14d'`, and `''`), defaults to…"},
			&cli.StringFlag{Name: "shortIdLookup", Usage: "query: If this is set to true then short IDs are looked up by this function as well. T…"},
			&cli.StringFlag{Name: "query", Usage: "query: An optional Sentry structured search query. If not provided an implied `'is:unr…"},
			&cli.StringFlag{Name: "hashes", Usage: "query: A list of hashes of groups to return. Is not compatible with 'query' parameter.…"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.events.list-a-project-s-issues",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("statsPeriod") {
						m["--statsPeriod"] = c.String("statsPeriod")
					}
					if c.IsSet("shortIdLookup") {
						m["--shortIdLookup"] = c.String("shortIdLookup")
					}
					if c.IsSet("query") {
						m["--query"] = c.String("query")
					}
					if c.IsSet("hashes") {
						m["--hashes"] = c.String("hashes")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/issues/"
					q := url.Values{}
					if c.IsSet("statsPeriod") {
						q.Set("statsPeriod", c.String("statsPeriod"))
					}
					if c.IsSet("shortIdLookup") {
						q.Set("shortIdLookup", c.String("shortIdLookup"))
					}
					if c.IsSet("query") {
						q.Set("query", c.String("query"))
					}
					if c.IsSet("hashes") {
						q.Set("hashes", c.String("hashes"))
					}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opEventsBulkMutateAListOfIssues(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "bulk-mutate-a-list-of-issues",
		Usage:     "Bulk mutate various attributes on issues. The list of issues to modify is given through the `id` query parameter. It is…",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "id", Usage: "query: A list of IDs of the issues to be mutated. This parameter shall be repeated for…"},
			&cli.StringFlag{Name: "status", Usage: "query: Optionally limits the query to issues of the specified status. Valid values are…"},
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.events.bulk-mutate-a-list-of-issues",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("id") {
						m["--id"] = c.String("id")
					}
					if c.IsSet("status") {
						m["--status"] = c.String("status")
					}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/issues/"
					q := url.Values{}
					if c.IsSet("id") {
						q.Set("id", c.String("id"))
					}
					if c.IsSet("status") {
						q.Set("status", c.String("status"))
					}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "PUT", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opEventsBulkRemoveAListOfIssues(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "bulk-remove-a-list-of-issues",
		Usage:     "Permanently remove the given issues. The list of issues to modify is given through the `id` query parameter. It is repe…",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "id", Usage: "query: A list of IDs of the issues to be removed. This parameter shall be repeated for…"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.events.bulk-remove-a-list-of-issues",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("id") {
						m["--id"] = c.String("id")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/issues/"
					q := url.Values{}
					if c.IsSet("id") {
						q.Set("id", c.String("id"))
					}
					var body []byte
					return doRequestAndStream(ctx, r, "DELETE", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opEventsListATagSValuesRelatedToAnIssue(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-a-tag-s-values-related-to-an-issue",
		Usage:     "Returns details for given tag key related to an issue. When [paginated](/api/pagination) can return at most 1000 values.",
		ArgsUsage: "<organization_id_or_slug> <issue_id> <key>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.events.list-a-tag-s-values-related-to-an-issue",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug issue_id key), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/organizations/" + p0 + "/issues/" + p1 + "/tags/" + p2 + "/values/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opEventsListAnIssueSHashes(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-an-issue-s-hashes",
		Usage:     "This endpoint lists an issue's hashes, which are the generated checksums used to aggregate individual events.",
		ArgsUsage: "<organization_id_or_slug> <issue_id>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "full", Usage: "query: If this is set to true, the event payload will include the full event body, inc…"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.events.list-an-issue-s-hashes",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("full") {
						m["--full"] = c.String("full")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug issue_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/organizations/" + p0 + "/issues/" + p1 + "/hashes/"
					q := url.Values{}
					if c.IsSet("full") {
						q.Set("full", c.String("full"))
					}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opEventsRetrieveAnIssue(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "retrieve-an-issue",
		Usage:     "Return details on an individual issue. This returns the basic stats for the issue (title, last seen, first seen), some…",
		ArgsUsage: "<organization_id_or_slug> <issue_id>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "collapse", Usage: "query: Fields to remove from the response to improve query performance."},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.events.retrieve-an-issue",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("collapse") {
						m["--collapse"] = c.String("collapse")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug issue_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/organizations/" + p0 + "/issues/" + p1 + "/"
					q := url.Values{}
					if c.IsSet("collapse") {
						q.Set("collapse", c.String("collapse"))
					}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opEventsUpdateAnIssue(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "update-an-issue",
		Usage:     "Updates an individual issue's attributes. Only the attributes submitted are modified.",
		ArgsUsage: "<organization_id_or_slug> <issue_id>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.events.update-an-issue",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug issue_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/organizations/" + p0 + "/issues/" + p1 + "/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "PUT", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opEventsRemoveAnIssue(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "remove-an-issue",
		Usage:     "Removes an individual issue.",
		ArgsUsage: "<organization_id_or_slug> <issue_id>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.events.remove-an-issue",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug issue_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/organizations/" + p0 + "/issues/" + p1 + "/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "DELETE", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opIntegrationListAnOrganizationSIntegrationPlatformInstallations(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-an-organization-s-integration-platform-installations",
		Usage:     "Return a list of integration platform installations for a given organization.",
		ArgsUsage: "<organization_id_or_slug>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.integration.list-an-organization-s-integration-platform-installations",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 1 {
						return fmt.Errorf("sentry: need 1 positional args (organization_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					path := "/api/0/organizations/" + p0 + "/sentry-app-installations/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opIntegrationCreateOrUpdateAnExternalIssue(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "create-or-update-an-external-issue",
		Usage:     "Create or update an external issue from an integration platform integration.",
		ArgsUsage: "<uuid>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.integration.create-or-update-an-external-issue",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 1 {
						return fmt.Errorf("sentry: need 1 positional args (uuid), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					path := "/api/0/sentry-app-installations/" + p0 + "/external-issues/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "POST", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opIntegrationDeleteAnExternalIssue(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "delete-an-external-issue",
		Usage:     "Delete an external issue.",
		ArgsUsage: "<uuid> <external_issue_id>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.integration.delete-an-external-issue",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (uuid external_issue_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/sentry-app-installations/" + p0 + "/external-issues/" + p1 + "/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "DELETE", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opOrganizationsListAnOrganizationSRepositories(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-an-organization-s-repositories",
		Usage:     "Return a list of version control repositories for a given organization.",
		ArgsUsage: "<organization_id_or_slug>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.organizations.list-an-organization-s-repositories",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 1 {
						return fmt.Errorf("sentry: need 1 positional args (organization_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					path := "/api/0/organizations/" + p0 + "/repos/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsListAProjectSDebugInformationFiles(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-a-project-s-debug-information-files",
		Usage:     "Retrieve a list of debug information files for a given project.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.list-a-project-s-debug-information-files",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/files/dsyms/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsUploadANewFile(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "upload-a-new-file",
		Usage:     "Upload a new debug information file for the given release. Unlike other API requests, files must be uploaded using the…",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.upload-a-new-file",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/files/dsyms/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "POST", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsDeleteASpecificProjectSDebugInformationFile(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "delete-a-specific-project-s-debug-information-file",
		Usage:     "Delete a debug information file for a given project.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "id", Usage: "query: The ID of the DIF to delete."},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.delete-a-specific-project-s-debug-information-file",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("id") {
						m["--id"] = c.String("id")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/files/dsyms/"
					q := url.Values{}
					if c.IsSet("id") {
						q.Set("id", c.String("id"))
					}
					var body []byte
					return doRequestAndStream(ctx, r, "DELETE", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsListAProjectSUsers(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-a-project-s-users",
		Usage:     "Return a list of users seen within this project.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "query", Usage: "query: Limit results to users matching the given query. Prefixes should be used to sug…"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.list-a-project-s-users",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("query") {
						m["--query"] = c.String("query")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/users/"
					q := url.Values{}
					if c.IsSet("query") {
						q.Set("query", c.String("query"))
					}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsListATagSValues(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-a-tag-s-values",
		Usage:     "Return a list of values associated with this key. The `query` parameter can be used to to perform a 'contains' match on…",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug> <key>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.list-a-tag-s-values",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug project_id_or_slug key), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/tags/" + p2 + "/values/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsRetrieveEventCountsForAProject(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "retrieve-event-counts-for-a-project",
		Usage:     "Caution This endpoint may change in the future without notice.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "stat", Usage: "query: The name of the stat to query `('received', 'rejected', 'blacklisted', 'generat…"},
			&cli.StringFlag{Name: "since", Usage: "query: A timestamp to set the start of the query in seconds since UNIX epoch."},
			&cli.StringFlag{Name: "until", Usage: "query: A timestamp to set the end of the query in seconds since UNIX epoch."},
			&cli.StringFlag{Name: "resolution", Usage: "query: An explicit resolution to search for (one of `10s`, `1h`, and `1d`)."},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.retrieve-event-counts-for-a-project",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("stat") {
						m["--stat"] = c.String("stat")
					}
					if c.IsSet("since") {
						m["--since"] = c.String("since")
					}
					if c.IsSet("until") {
						m["--until"] = c.String("until")
					}
					if c.IsSet("resolution") {
						m["--resolution"] = c.String("resolution")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/stats/"
					q := url.Values{}
					if c.IsSet("stat") {
						q.Set("stat", c.String("stat"))
					}
					if c.IsSet("since") {
						q.Set("since", c.String("since"))
					}
					if c.IsSet("until") {
						q.Set("until", c.String("until"))
					}
					if c.IsSet("resolution") {
						q.Set("resolution", c.String("resolution"))
					}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsListAProjectSUserFeedback(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-a-project-s-user-feedback",
		Usage:     "Return a list of user feedback items within this project. *This list does not include submissions from the [User Feedba…",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.list-a-project-s-user-feedback",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/user-feedback/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsSubmitUserFeedback(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "submit-user-feedback",
		Usage:     "*This endpoint is DEPRECATED. We document it here for older SDKs and users who are still migrating to the [User Feedbac…",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.submit-user-feedback",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/user-feedback/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "POST", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsListAProjectSServiceHooks(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-a-project-s-service-hooks",
		Usage:     "Return a list of service hooks bound to a project.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.list-a-project-s-service-hooks",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/hooks/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsRegisterANewServiceHook(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "register-a-new-service-hook",
		Usage:     "Register a new service hook on a project. Events include: - event.alert: An alert is generated for an event (via rules)…",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.register-a-new-service-hook",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug project_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/hooks/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "POST", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsRetrieveAServiceHook(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "retrieve-a-service-hook",
		Usage:     "Return a service hook bound to a project.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug> <hook_id>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.retrieve-a-service-hook",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug project_id_or_slug hook_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/hooks/" + p2 + "/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsUpdateAServiceHook(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "update-a-service-hook",
		Usage:     "Update a service hook.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug> <hook_id>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.update-a-service-hook",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug project_id_or_slug hook_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/hooks/" + p2 + "/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "PUT", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsRemoveAServiceHook(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "remove-a-service-hook",
		Usage:     "Remove a service hook.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug> <hook_id>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.remove-a-service-hook",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug project_id_or_slug hook_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/hooks/" + p2 + "/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "DELETE", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsEnableSpikeProtection(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "enable-spike-protection",
		Usage:     "Enables Spike Protection feature for some of the projects within the organization.",
		ArgsUsage: "<organization_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.enable-spike-protection",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 1 {
						return fmt.Errorf("sentry: need 1 positional args (organization_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					path := "/api/0/organizations/" + p0 + "/spike-protections/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "POST", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opProjectsDisableSpikeProtection(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "disable-spike-protection",
		Usage:     "Disables Spike Protection feature for some of the projects within the organization.",
		ArgsUsage: "<organization_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.projects.disable-spike-protection",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 1 {
						return fmt.Errorf("sentry: need 1 positional args (organization_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					path := "/api/0/organizations/" + p0 + "/spike-protections/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "DELETE", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesListAnOrganizationSReleases(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-an-organization-s-releases",
		Usage:     "Return a list of releases for a given organization.",
		ArgsUsage: "<organization_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "query", Usage: "query: This parameter can be used to create a 'starts with' filter for the version."},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.list-an-organization-s-releases",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("query") {
						m["--query"] = c.String("query")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 1 {
						return fmt.Errorf("sentry: need 1 positional args (organization_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					path := "/api/0/organizations/" + p0 + "/releases/"
					q := url.Values{}
					if c.IsSet("query") {
						q.Set("query", c.String("query"))
					}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesCreateANewReleaseForAnOrganization(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "create-a-new-release-for-an-organization",
		Usage:     "Create a new release for the given organization. Releases are used by Sentry to improve its error reporting abilities b…",
		ArgsUsage: "<organization_id_or_slug>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.create-a-new-release-for-an-organization",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 1 {
						return fmt.Errorf("sentry: need 1 positional args (organization_id_or_slug), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					path := "/api/0/organizations/" + p0 + "/releases/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "POST", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesListAnOrganizationSReleaseFiles(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-an-organization-s-release-files",
		Usage:     "Return a list of files for a given release.",
		ArgsUsage: "<organization_id_or_slug> <version>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.list-an-organization-s-release-files",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug version), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/organizations/" + p0 + "/releases/" + p1 + "/files/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesUploadANewOrganizationReleaseFile(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "upload-a-new-organization-release-file",
		Usage:     "Upload a new file for the given release. Unlike other API requests, files must be uploaded using the traditional multip…",
		ArgsUsage: "<organization_id_or_slug> <version>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.upload-a-new-organization-release-file",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug version), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/organizations/" + p0 + "/releases/" + p1 + "/files/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "POST", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesListAProjectSReleaseFiles(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-a-project-s-release-files",
		Usage:     "Return a list of files for a given release.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug> <version>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.list-a-project-s-release-files",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug project_id_or_slug version), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/releases/" + p2 + "/files/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesUploadANewProjectReleaseFile(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "upload-a-new-project-release-file",
		Usage:     "Upload a new file for the given release. Unlike other API requests, files must be uploaded using the traditional multip…",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug> <version>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.upload-a-new-project-release-file",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug project_id_or_slug version), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/releases/" + p2 + "/files/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "POST", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesRetrieveAnOrganizationReleaseSFile(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "retrieve-an-organization-release-s-file",
		Usage:     "Retrieve a file for a given release.",
		ArgsUsage: "<organization_id_or_slug> <version> <file_id>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "download", Usage: "query: If this is set to true, then the response payload will be the raw file contents…"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.retrieve-an-organization-release-s-file",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("download") {
						m["--download"] = c.String("download")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug version file_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/organizations/" + p0 + "/releases/" + p1 + "/files/" + p2 + "/"
					q := url.Values{}
					if c.IsSet("download") {
						q.Set("download", c.String("download"))
					}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesUpdateAnOrganizationReleaseFile(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "update-an-organization-release-file",
		Usage:     "Update an organization release file.",
		ArgsUsage: "<organization_id_or_slug> <version> <file_id>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.update-an-organization-release-file",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug version file_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/organizations/" + p0 + "/releases/" + p1 + "/files/" + p2 + "/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "PUT", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesDeleteAnOrganizationReleaseSFile(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "delete-an-organization-release-s-file",
		Usage:     "Delete a file for a given release.",
		ArgsUsage: "<organization_id_or_slug> <version> <file_id>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.delete-an-organization-release-s-file",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug version file_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/organizations/" + p0 + "/releases/" + p1 + "/files/" + p2 + "/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "DELETE", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesRetrieveAProjectReleaseSFile(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "retrieve-a-project-release-s-file",
		Usage:     "Retrieve a file for a given release.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug> <version> <file_id>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "download", Usage: "query: If this is set to true, then the response payload will be the raw file contents…"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.retrieve-a-project-release-s-file",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("download") {
						m["--download"] = c.String("download")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 4 {
						return fmt.Errorf("sentry: need 4 positional args (organization_id_or_slug project_id_or_slug version file_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					p3 := url.PathEscape(args[3])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/releases/" + p2 + "/files/" + p3 + "/"
					q := url.Values{}
					if c.IsSet("download") {
						q.Set("download", c.String("download"))
					}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesUpdateAProjectReleaseFile(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "update-a-project-release-file",
		Usage:     "Update a project release file.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug> <version> <file_id>",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "body", Usage: "JSON body, '@file', or '-' for stdin"},
		},
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.update-a-project-release-file",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					if c.IsSet("body") {
						m["--body"] = c.String("body")
					}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 4 {
						return fmt.Errorf("sentry: need 4 positional args (organization_id_or_slug project_id_or_slug version file_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					p3 := url.PathEscape(args[3])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/releases/" + p2 + "/files/" + p3 + "/"
					q := url.Values{}
					body, err := readBody(c.String("body"))
					if err != nil {
						return err
					}
					return doRequestAndStream(ctx, r, "PUT", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesDeleteAProjectReleaseSFile(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "delete-a-project-release-s-file",
		Usage:     "Delete a file for a given release.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug> <version> <file_id>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.delete-a-project-release-s-file",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 4 {
						return fmt.Errorf("sentry: need 4 positional args (organization_id_or_slug project_id_or_slug version file_id), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					p3 := url.PathEscape(args[3])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/releases/" + p2 + "/files/" + p3 + "/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "DELETE", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesListAnOrganizationReleaseSCommits(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-an-organization-release-s-commits",
		Usage:     "List an organization release's commits.",
		ArgsUsage: "<organization_id_or_slug> <version>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.list-an-organization-release-s-commits",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug version), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/organizations/" + p0 + "/releases/" + p1 + "/commits/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesListAProjectReleaseSCommits(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "list-a-project-release-s-commits",
		Usage:     "List a project release's commits.",
		ArgsUsage: "<organization_id_or_slug> <project_id_or_slug> <version>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.list-a-project-release-s-commits",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 3 {
						return fmt.Errorf("sentry: need 3 positional args (organization_id_or_slug project_id_or_slug version), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					p2 := url.PathEscape(args[2])
					path := "/api/0/projects/" + p0 + "/" + p1 + "/releases/" + p2 + "/commits/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

func opReleasesRetrieveFilesChangedInAReleaseSCommits(r *shell.Runner, w *audit.Writer) *cli.Command {
	return &cli.Command{
		Name:      "retrieve-files-changed-in-a-release-s-commits",
		Usage:     "Retrieve files changed in a release's commits",
		ArgsUsage: "<organization_id_or_slug> <version>",
		Action: verb.Wrap(
			verb.Spec{
				Name: "ops.sentry.releases.retrieve-files-changed-in-a-release-s-commits",
				ArgsFunc: func(c *cli.Command) (map[string]string, []string) {
					m := map[string]string{}
					return m, c.Args().Slice()
				},
				Action: func(ctx context.Context, c *cli.Command) error {
					args := c.Args().Slice()
					if len(args) != 2 {
						return fmt.Errorf("sentry: need 2 positional args (organization_id_or_slug version), got %d", len(args))
					}
					p0 := url.PathEscape(args[0])
					p1 := url.PathEscape(args[1])
					path := "/api/0/organizations/" + p0 + "/releases/" + p1 + "/commitfiles/"
					q := url.Values{}
					var body []byte
					return doRequestAndStream(ctx, r, "GET", path, q, body, true)
				},
			},
			w,
		),
	}
}

// readBody resolves the --body flag: literal JSON, '@path' for file,
// '-' for stdin. Empty input returns nil.
func readBody(spec string) ([]byte, error) {
	switch {
	case spec == "":
		return nil, nil
	case spec == "-":
		b, err := io.ReadAll(os.Stdin)
		if err != nil {
			return nil, fmt.Errorf("sentry: read stdin: %w", err)
		}
		return b, nil
	case strings.HasPrefix(spec, "@"):
		b, err := os.ReadFile(spec[1:])
		if err != nil {
			return nil, fmt.Errorf("sentry: read %s: %w", spec[1:], err)
		}
		return b, nil
	default:
		return []byte(spec), nil
	}
}

func doRequestAndStream(ctx context.Context, r *shell.Runner, method, path string, q url.Values, body []byte, authNeeded bool) error {
	target := apiBase + path
	if len(q) > 0 {
		target += "?" + q.Encode()
	}
	var rdr io.Reader
	if len(body) > 0 {
		rdr = bytes.NewReader(body)
	}
	req, err := http.NewRequestWithContext(ctx, method, target, rdr)
	if err != nil {
		return fmt.Errorf("sentry: build request: %w", err)
	}
	if len(body) > 0 {
		req.Header.Set("Content-Type", "application/json")
	}
	req.Header.Set("Accept", "application/json")
	if authNeeded {
		key, err := fetchSSM(ctx, r, ssmAPIKey)
		if err != nil {
			return err
		}
		req.Header.Set("Authorization", "Bearer "+key)
	}

	client := &http.Client{Timeout: httpTimeout}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("sentry: request: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("sentry: read response: %w", err)
	}
	if resp.StatusCode >= 400 {
		return fmt.Errorf("sentry: HTTP %d: %s", resp.StatusCode, strings.TrimSpace(string(raw)))
	}
	if len(bytes.TrimSpace(raw)) == 0 {
		return nil
	}
	var pretty json.RawMessage
	if err := json.Unmarshal(raw, &pretty); err != nil {
		_, _ = os.Stdout.Write(raw)
		return nil
	}
	out, err := json.MarshalIndent(pretty, "", "  ")
	if err != nil {
		return fmt.Errorf("sentry: re-encode response: %w", err)
	}
	if _, err := fmt.Fprintln(os.Stdout, string(out)); err != nil {
		return err
	}
	return nil
}

func fetchSSM(ctx context.Context, r *shell.Runner, name string) (string, error) {
	out, err := r.Capture(ctx, "aws",
		"ssm", "get-parameter",
		"--name", name,
		"--with-decryption",
		"--query", "Parameter.Value",
		"--output", "text",
	)
	if err != nil {
		return "", fmt.Errorf("sentry: fetch %s: %w", name, err)
	}
	v := strings.TrimSpace(string(out))
	if v == "" {
		return "", fmt.Errorf("sentry: %s resolved to empty value", name)
	}
	return v, nil
}
