package lockdown

import (
	"fmt"
	"sort"
	"strings"
)

// HookFileName is the basename of the generated PreToolUse Bash hook script.
// Lives next to settings.json under .claude/.
const HookFileName = "lockdown-deny.sh"

// UserHookFileName is the basename of the user-level PreToolUse Bash hook
// installed by `coily setup`. Distinct name from HookFileName so it cannot
// collide with a per-repo lockdown-deny.sh discovered via cwd-relative
// resolution. Lives at ~/.claude/<this>.
const UserHookFileName = "coily-binary-gate.sh"

// CoilyAllowedPaths is the closed set of filesystem paths a `coily` invocation
// is permitted to resolve to. Anything else (including ~/go/bin/coily,
// /tmp/foo/coily, ./bin/coily) is rejected by the hook. The list covers
// homebrew on Apple Silicon, homebrew on Intel macOS, and Linuxbrew on
// Linux (kai-server). The hook follows the bin/coily symlink Brew lays
// down rather than the Cellar realpath, because `command -v coily`
// returns the symlink path.
var CoilyAllowedPaths = []string{
	"/opt/homebrew/bin/coily",              // Apple Silicon homebrew
	"/usr/local/bin/coily",                 // Intel macOS homebrew
	"/home/linuxbrew/.linuxbrew/bin/coily", // Linuxbrew default prefix
}

// HookSettingsPath is the value baked into settings.json's hook entry. Claude
// Code resolves it relative to the project root (the directory containing
// .claude/settings.json), which keeps the generated settings portable across
// machines.
const HookSettingsPath = ".claude/" + HookFileName

// renderCoilyBinaryCheck emits the shell block that rejects coily
// invocations outside the homebrew install paths. Lives between the env
// strip and the deny-prefix case statement in the generated hook.
// Catches both bare-name (`coily ...` resolved via `command -v`) and
// explicit-path forms (any `*/coily` segment leading token).
func renderCoilyBinaryCheck() string {
	allowed := strings.Join(CoilyAllowedPaths, ", ")
	var b strings.Builder
	b.WriteString(`  # Coily binary check: reject any invocation that resolves to a coily
  # binary outside the homebrew install paths. Catches bare-name (PATH
  # lookup) and explicit-path forms (absolute or */coily). This is a
  # content-based check, not a leading-token literal match, so it lives
  # outside the case statement below.
  seg_first=${seg%% *}
  case "$seg_first" in
    coily)
      coily_path=$(command -v coily 2>/dev/null || true)
      case "$coily_path" in
        "") ;; # not on PATH; let bash report command-not-found
`)
	for _, p := range CoilyAllowedPaths {
		fmt.Fprintf(&b, "        %q) ;;\n", p)
	}
	fmt.Fprintf(&b, "        *) printf 'lockdown: blocked: coily resolves to %%s, which is not a homebrew install (allowed: %s)\\n' \"$coily_path\" >&2; exit 2 ;;\n", allowed)
	b.WriteString(`      esac
      ;;
    */coily)
      case "$seg_first" in
`)
	for _, p := range CoilyAllowedPaths {
		fmt.Fprintf(&b, "        %q) ;;\n", p)
	}
	fmt.Fprintf(&b, "        *) printf 'lockdown: blocked: coily binary at %%s is not a homebrew install (allowed: %s)\\n' \"$seg_first\" >&2; exit 2 ;;\n", allowed)
	b.WriteString(`      esac
      ;;
  esac
`)
	return b.String()
}

// renderHookHeader emits the script preamble: shebang, header comment,
// stdin parse, segment split, and check_segment open through env strip.
func renderHookHeader() string {
	return `#!/bin/sh
# Auto-generated by coily. Do not edit; regenerate via coily setup or
# coily lockdown --apply --replace.
#
# PreToolUse Bash hook for Claude Code Desktop, where the built-in
# permissions.deny matcher is silently bypassed (verified 2026-04-23 on
# v2.1.119). On the CLI the built-in matcher is the primary gate; this
# hook is defense-in-depth there. On Desktop this hook is the only gate.
#
# Reads tool-input JSON on stdin, extracts tool_input.command, splits on
# common shell separators, strips leading "env VAR=val" tokens, then
# applies content-based and prefix-based deny checks. Exits 2 with a
# stderr message on hit.

set -u

INPUT=$(cat)
# Pull tool_input.command via a single-line sed. JSON parsing in pure sh
# is fragile; this matches Claude Code's well-formed input. Backslash-
# escapes in the original command are not unescaped here - the leading-
# token compare is robust to that as long as the binary name itself does
# not contain escapes (it never does in practice).
CMD=$(printf '%s' "$INPUT" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
if [ -z "$CMD" ]; then
  exit 0
fi

# Split CMD into segments at shell separators. A segment is the leading
# command of a pipeline / boolean / sequence / command substitution.
SEGMENTS=$(printf '%s\n' "$CMD" | awk '
{
  s = $0
  gsub(/\$\(/, "\n", s)
  gsub(/\)/,   "\n", s)
  gsub(/\|\|/, "\n", s)
  gsub(/&&/,   "\n", s)
  gsub(/[|;&]/, "\n", s)
  print s
}')

check_segment() {
  seg=$1
  # Strip leading whitespace.
  seg=$(printf '%s' "$seg" | sed -E 's/^[[:space:]]+//')
  [ -z "$seg" ] && return 0
  # Strip leading "env VAR=val ..." tokens (env on its own is denied
  # anyway, but env-prefixed invocations of an allowed binary should be
  # tested against the underlying binary).
  while printf '%s' "$seg" | grep -qE '^env( +[A-Za-z_][A-Za-z0-9_]*=[^ ]+)+( +|$)'; do
    seg=$(printf '%s' "$seg" | sed -E 's/^env( +[A-Za-z_][A-Za-z0-9_]*=[^ ]+)+( +|$)//')
  done
`
}

// renderHookFooter emits the closing brace of check_segment and the
// segment-iteration loop.
func renderHookFooter() string {
	return `}

# Iterate segments. heredoc is a single-process loop so an exit inside
# check_segment terminates the whole script.
while IFS= read -r seg; do
  check_segment "$seg"
done <<EOF
$SEGMENTS
EOF

exit 0
`
}

// wrapperRecovery maps a denied bare-binary leading-token to the coily
// wrapper that should be used instead. When a deny rule fires for a binary
// with a wrapper, the deny message names the wrapper as the recovery path
// per AGENTS.md "opaque errors are design smells - recovery messages should
// name the command or skill Kai can dictate next." Issue #61.
var wrapperRecovery = map[string]string{
	"gh":        "coily ops gh",
	"aws":       "coily ops aws",
	"kubectl":   "coily ops kubectl",
	"docker":    "coily docker",
	"tailscale": "coily tailscale",
}

// renderDenyPrefixCase emits the case statement that matches each deny
// prefix as the segment's leading token (with or without trailing args).
func renderDenyPrefixCase(prefixes []string) string {
	var b strings.Builder
	b.WriteString("  case \"$seg\" in\n")
	for _, p := range prefixes {
		// case patterns: literal-quoted prefix and prefix-followed-by-space.
		// POSIX sh interprets "..." as literal in case patterns.
		msg := fmt.Sprintf("lockdown: blocked by deny rule: %s", p)
		if rec, ok := wrapperRecovery[p]; ok {
			msg = fmt.Sprintf("%s. Recovery: use `%s ...` (audited wrapper).", msg, rec)
		}
		fmt.Fprintf(&b, "    %q|%q*) printf '%s\\n' >&2; exit 2 ;;\n",
			p, p+" ", msg)
	}
	b.WriteString("  esac\n")
	return b.String()
}

// extractBashDenyPrefixes pulls the leading-token shape out of every
// Bash(<prefix>:*) entry in the deny list. Other shapes (PowerShell,
// PowerShell(*), bare strings) are skipped - the hook only gates the Bash
// tool, the same surface Claude Code's built-in matcher gates.
func extractBashDenyPrefixes(deny []string) []string {
	const pre = "Bash("
	const suf = ":*)"
	seen := map[string]bool{}
	out := make([]string, 0, len(deny))
	for _, rule := range deny {
		if !strings.HasPrefix(rule, pre) || !strings.HasSuffix(rule, suf) {
			continue
		}
		prefix := strings.TrimSuffix(strings.TrimPrefix(rule, pre), suf)
		if prefix == "" || seen[prefix] {
			continue
		}
		seen[prefix] = true
		out = append(out, prefix)
	}
	sort.Strings(out)
	return out
}

// RenderHookScript emits the per-repo PreToolUse hook: header + coily
// binary check + deny-prefix case + footer. Re-run
// `coily lockdown --apply --replace` to regenerate after the deny list
// changes; the contract is one regen per coily release.
//
// TODO: revisit once Claude Code Desktop honors permissions.deny again.
// Tracking issues upstream:
//   - https://github.com/anthropics/claude-code/issues/29026 (Desktop
//     ignores settings.json permissions on macOS)
//   - https://github.com/anthropics/claude-code/issues/38662 (Desktop
//     ignores bypassPermissions; same matcher path)
//
// When the upstream Bash matcher fires on Desktop, this whole script
// becomes dead weight on the CLI (defense-in-depth there) and removable
// outright on Desktop.
func RenderHookScript(d *Defaults) (string, error) {
	prefixes := extractBashDenyPrefixes(d.Deny)
	if len(prefixes) == 0 {
		return "", fmt.Errorf("lockdown: no Bash(...:*) deny rules to render")
	}
	return renderHookHeader() + renderCoilyBinaryCheck() + renderDenyPrefixCase(prefixes) + renderHookFooter(), nil
}

// RenderUserHookScript emits the user-level PreToolUse hook: header +
// coily binary check + footer (no deny-prefix case). Installed at
// ~/.claude/coily-binary-gate.sh by `coily setup`. Catches dev coily
// invocations from any cwd, complementing the per-repo hook which only
// fires inside coily-managed repos.
func RenderUserHookScript() string {
	return renderHookHeader() + renderCoilyBinaryCheck() + renderHookFooter()
}
