package lockdown

import (
	"fmt"
	"sort"
	"strings"
)

// HookFileName is the basename of the generated PreToolUse Bash hook script.
// Lives next to settings.json under .claude/.
const HookFileName = "lockdown-deny.sh"

// HookSettingsPath is the value baked into settings.json's hook entry. Claude
// Code resolves it relative to the project root (the directory containing
// .claude/settings.json), which keeps the generated settings portable across
// machines.
const HookSettingsPath = ".claude/" + HookFileName

// extractBashDenyPrefixes pulls the leading-token shape out of every
// Bash(<prefix>:*) entry in the deny list. Other shapes (PowerShell,
// PowerShell(*), bare strings) are skipped - the hook only gates the Bash
// tool, the same surface Claude Code's built-in matcher gates.
func extractBashDenyPrefixes(deny []string) []string {
	const pre = "Bash("
	const suf = ":*)"
	seen := map[string]bool{}
	out := make([]string, 0, len(deny))
	for _, rule := range deny {
		if !strings.HasPrefix(rule, pre) || !strings.HasSuffix(rule, suf) {
			continue
		}
		prefix := strings.TrimSuffix(strings.TrimPrefix(rule, pre), suf)
		if prefix == "" || seen[prefix] {
			continue
		}
		seen[prefix] = true
		out = append(out, prefix)
	}
	sort.Strings(out)
	return out
}

// RenderHookScript emits the POSIX sh body that backs the PreToolUse Bash
// hook. The script reads Claude Code's tool-input JSON on stdin, extracts
// tool_input.command, and matches the leading token of each segment
// (split at "|", "&&", "||", ";", "&", "$(", ")") against the deny list
// baked in below. Exits 2 with a stderr message on hit.
//
// The script is generated, not invoked through coily, so there is no
// per-Bash-call subprocess overhead beyond /bin/sh starting up. Re-run
// `coily lockdown --apply --replace` to regenerate after the deny list
// changes; the contract is one regen per coily release.
//
// TODO: revisit once Claude Code Desktop honors permissions.deny again.
// Tracking issues upstream:
//   - https://github.com/anthropics/claude-code/issues/29026 (Desktop
//     ignores settings.json permissions on macOS)
//   - https://github.com/anthropics/claude-code/issues/38662 (Desktop
//     ignores bypassPermissions; same matcher path)
//
// When the upstream Bash matcher fires on Desktop, this whole script
// becomes dead weight on the CLI (defense-in-depth there) and removable
// outright on Desktop. Test before deleting: stage a deny rule, run a
// matching command in Desktop agent mode, confirm the built-in matcher
// blocks it without the hook installed.
func RenderHookScript(d *Defaults) (string, error) {
	prefixes := extractBashDenyPrefixes(d.Deny)
	if len(prefixes) == 0 {
		return "", fmt.Errorf("lockdown: no Bash(...:*) deny rules to render")
	}

	var b strings.Builder
	b.WriteString(`#!/bin/sh
# Auto-generated by coily lockdown. Do not edit; regenerate with
#   coily lockdown --apply --replace
#
# PreToolUse Bash hook for Claude Code Desktop, where the built-in
# permissions.deny matcher is silently bypassed (verified 2026-04-23 on
# v2.1.119). On the CLI the built-in matcher is the primary gate; this
# hook is defense-in-depth there. On Desktop this hook is the only gate.
#
# Reads tool-input JSON on stdin, extracts tool_input.command, splits on
# common shell separators, strips leading "env VAR=val" tokens, then
# tests the leading token of each segment against the deny prefixes
# below. Exits 2 with a stderr message on hit.

set -u

INPUT=$(cat)
# Pull tool_input.command via a single-line sed. JSON parsing in pure sh
# is fragile; this matches Claude Code's well-formed input. Backslash-
# escapes in the original command are not unescaped here - the leading-
# token compare is robust to that as long as the binary name itself does
# not contain escapes (it never does in practice).
CMD=$(printf '%s' "$INPUT" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
if [ -z "$CMD" ]; then
  exit 0
fi

# Split CMD into segments at shell separators. A segment is the leading
# command of a pipeline / boolean / sequence / command substitution.
SEGMENTS=$(printf '%s\n' "$CMD" | awk '
{
  s = $0
  gsub(/\$\(/, "\n", s)
  gsub(/\)/,   "\n", s)
  gsub(/\|\|/, "\n", s)
  gsub(/&&/,   "\n", s)
  gsub(/[|;&]/, "\n", s)
  print s
}')

check_segment() {
  seg=$1
  # Strip leading whitespace.
  seg=$(printf '%s' "$seg" | sed -E 's/^[[:space:]]+//')
  [ -z "$seg" ] && return 0
  # Strip leading "env VAR=val ..." tokens (env on its own is denied
  # anyway, but env-prefixed invocations of an allowed binary should be
  # tested against the underlying binary).
  while printf '%s' "$seg" | grep -qE '^env( +[A-Za-z_][A-Za-z0-9_]*=[^ ]+)+( +|$)'; do
    seg=$(printf '%s' "$seg" | sed -E 's/^env( +[A-Za-z_][A-Za-z0-9_]*=[^ ]+)+( +|$)//')
  done
  case "$seg" in
`)
	for _, p := range prefixes {
		// case patterns: literal-quoted prefix and prefix-followed-by-space.
		// POSIX sh interprets "..." as literal in case patterns.
		fmt.Fprintf(&b, "    %q|%q*) printf 'lockdown: blocked by deny rule: %s\\n' >&2; exit 2 ;;\n",
			p, p+" ", p)
	}
	b.WriteString(`  esac
}

# Iterate segments. heredoc is a single-process loop so an exit inside
# check_segment terminates the whole script.
while IFS= read -r seg; do
  check_segment "$seg"
done <<EOF
$SEGMENTS
EOF

exit 0
`)
	return b.String(), nil
}
